Fix FileExist utility and generate sha for modelspec
kubeflow/kfserving pull request #1318
Opened 2021-01-26 13:48 UTC by yuzisun

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1203 

**Special notes for your reviewer**:

1. Generate sha for the model spec instead of individual fields
2. Fix FileExist util function as there could be other PathError if not `FileNotExist`

**Release note**:

```release-note

```

2021-01-26 13:59 UTC, yuzisun commented
/cc @yuzliu @abchoo

2021-01-26 17:30 UTC, ifilonenko requested changes

2021-01-26 17:30 UTC, ifilonenko commented on pkg/agent/downloader.go
> +		sha256 := storage.AsSha256(modelSpec)
if we are changing hashing strategy the unhashing needs to be handled as well

2021-02-01 02:10 UTC, rmporsch commented
Thanks so much @yuzisun for taking care of this!

2021-02-01 15:49 UTC, yuzliu commented
/LGTM

2021-02-01 15:51 UTC, merged