Make kative local gateway configurable
kubeflow/kfserving pull request #1363
Opened 2021-02-06 18:52 UTC by yuzisun

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1340 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Added knative local gateway to the inference service config file
```

2021-02-06 20:34 UTC, theofpa requested changes
Shouldn't we use the new localGateway convention of knative (`knative-local-gateway`) as the default value, and users of old versions can change that to `cluster-local-gateway`?

2021-02-06 20:34 UTC, theofpa commented on config/configmap/inferenceservice.yaml
> +        "localGatewayService" : "cluster-local-gateway.istio-system.svc.cluster.local"
```suggestion
        "localGateway" : "knative-local-gateway"
        "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local"
```

2021-02-06 20:34 UTC, theofpa commented on config/overlays/test/configmap/inferenceservice.yaml
> +        "localGatewayService" : "cluster-local-gateway.istio-system.svc.cluster.local"
```suggestion
        "localGateway": "knative-local-gateway.knative-serving",
        "localGatewayService" : "knative-local-gateway.istio-system.svc.cluster.local"
```

2021-02-06 20:34 UTC, theofpa commented on pkg/controller/v1beta1/inferenceservice/controller_test.go
> +               "localGatewayService": "cluster-local-gateway.istio-system.svc.cluster.local"
```suggestion
               "localGateway": "knative-serving/knative-local-gateway",
               "localGatewayService": "knative-local-gateway.istio-system.svc.cluster.local"
```

2021-02-06 20:34 UTC, theofpa commented on pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go
> +				LocalGatewayServiceName: "cluster-local-gateway.istio-system.svc.cluster.local",
```suggestion
				LocalGatewayServiceName: "knative-local-gateway.istio-system.svc.cluster.local",
```

2021-02-06 20:46 UTC, yuzisun commented
> Shouldn't we use the new localGateway convention of knative (`knative-local-gateway`) as the default value, and users of old versions can change that to `cluster-local-gateway`?

@theofpa Yes let’s do that in your PR, I want to first make it configurable and run the e2e rests to confirm it works with the old value.

2021-02-06 20:53 UTC, theofpa commented
> > Shouldn't we use the new localGateway convention of knative (`knative-local-gateway`) as the default value, and users of old versions can change that to `cluster-local-gateway`?
> 
> @theofpa Yes let’s do that in your PR, I want to first make it configurable and run the e2e rests to confirm it works with the old value against older knative version as you are upgrading knative version in e2e.

ok!
/lgtm

2021-02-06 20:55 UTC, merged

2021-02-09 22:31 UTC, theofpa commented on pkg/apis/serving/v1beta1/configmap.go
> +	LocalGatewayServiceName string `json:"localGatewayService,omitempty"`
@yuzisun, I've missed that, but it generates a name mismatch violation in the `make generate`. We can either match the names or add it in the violation exceptions.

2021-02-09 23:48 UTC, theofpa commented on config/configmap/inferenceservice.yaml
> +        "localGateway" : "cluster-local-gateway"
missing commas for valid json